### ISSUE TITLE
Readme inconsitency

### ISSUE THREAD

**Issue by shilbert01** [maxbachmann-magicmirror2/MMM-HideShowMove#2]
The sample config for mqtt-mm2-bridge list the port a 8883. I believe this is a type and should read 1883 instead. At least this is give as default in the code. Sure, you could set this to any port but then your mqtt broker needs to run on this port as well.

**Comment by maxbachmann** [comment]
It actually is not but I agree it might lead to some misunderstandings.
When you do not set port the default value is 1883.
Whats shown as example here is a config that shows the use of port when the broker is not on port 1883 but on port 8883. I will make this more clear in the description

**Comment by maxbachmann** [comment]
Please check wether it´s better now, or wether it´s still not clear enough :)

**Comment by maxbachmann** [comment]
I assume this is fixed
