### ISSUE TITLE
Show Pages not work

### ISSUE THREAD

**Issue by Ogg3l** [maxbachmann-magicmirror2/MMM-HideShowMove#5]
Hey Max,

First, thank you for your Implementation :) 

I tested it and i noticed that for example the command "Show Page One" not work. I studied your code and i think there is a little mistake:

In the Method showModule() i think it should be:
if (this.config[modulename.toString()].indexOf(**module.name**) > -1) 

rather than

if (this.config[modulename.toString()].indexOf(**module**) > -1)

I tested it an with this change it works.

Greetings from North Germany :)
Markus

**Comment by maxbachmann** [comment]
Hey Markus,

Thank you for finding this. I just fixed it

Greetings from South Germany ;)
Max
